@startuml DriveFlow_Diagrama_Estados
left to right direction
skinparam nodesep 60
skinparam ranksep 90
skinparam shadowing false
skinparam roundcorner 8
skinparam state {
    BackgroundColor White
    ArrowColor #333333
    BorderColor #555555
}
skinparam note {
    BackgroundColor White
    BorderColor #555555
}

title Diagrama de Estados Completo: Ciclo de Vida da Reserva (DriveFlow)

[*] --> AguardandoPagamento : solicitarReserva()

state AguardandoPagamento
AguardandoPagamento : entry / registrarLogInicial()
AguardandoPagamento : do / aguardarAcaoCliente()

AguardandoPagamento --> Validacao : processarPagamento()
AguardandoPagamento --> Cancelada : cancelarReserva() [pelo Cliente]

state Validacao <<choice>>
note bottom of Validacao
  Validação de saldo
  e fraude via Gateway
  Externo.
end note

Validacao --> Confirmada : [pagamentoAprovado]
Validacao --> Cancelada : [pagamentoRecusado]

state Confirmada
Confirmada : entry / notificarCliente()
Confirmada : do / alocarVeiculoEstoque()
Confirmada : exit / emitirVoucher()

Confirmada --> EmAndamento : realizarCheckOut()
Confirmada --> Cancelada : cancelarReserva() [com antecedência]

state EmAndamento
EmAndamento : entry / registrarSaidaVeiculo()
EmAndamento : do / monitorarPrazoContrato()

EmAndamento --> Finalizada : realizarCheckIn()

state Finalizada
Finalizada : entry / registrarVistoriaDevolucao()
Finalizada : do / calcularTaxasExtras()
Finalizada : exit / arquivarContrato()

state Cancelada
Cancelada : entry / liberarVeiculoEstoque()
Cancelada : do / processarEstornoSeAplicavel()

Finalizada --> [*]
Cancelada --> [*]

@enduml